### ISSUE TITLE
Add a generic 'ppc' (or similar named) function

### ISSUE THREAD

**Issue by paul-buerkner** [jgabry/ppcheck#2]
Likely developers of other packages will want to introduce a convenience function that generates the yreps and calls the pcc_* functions afterwards. As this will likely happen via S3 methods, it might be a good idea to put the corresponding generic in the ppcheck package to make sure that all packages use the same method name (to minimize confusion of users) and to avoid unnecessary function masking.

**Comment by jgabry** [comment]
Yeah I think that's a good idea. Were you just thinking of something
like ppc(object,
...)?

**Comment by paul-buerkner** [comment]
Exactly :-)
Am 22.05.2016 20:56 schrieb "Jonah Gabry" <notifications@github.com>:

**Comment by jgabry** [comment]
Ok added the generic. Not sure if I'll end up calling it `ppc`, `ppcheck`, `pp_check`, or whatever, but for now it's `ppc`.
