### ISSUE TITLE
Improve input checking for arguments 'y' and 'yrep'

### ISSUE THREAD

**Issue by paul-buerkner** [jgabry/ppcheck#3]
Right now, only vectors are excepted for `y` and matrices for `yrep`. In my point of view this may be too restrictive for a user facing function. For instance, one-dimensional arrays are not allowed as input for `y` although they look the same as vectors on the surface and users will wonder why there input is invalid. 
Maybe one could try to internally coerce `y` and `yrep` to a vector / matrix respectively thus allowing more flexible input. However, I also understand if you want to keep the input more restrictive.

Also, it may be good to check that both `y` and `yrep` are really numeric before passing them to ggplot2. For instance, when I call `ppc_resid` with a character vector for `y`, I get the error message 
`Error in FUN(x, aperm(array(STATS, dims[perm]), order(perm)), ...) : 
  non-numeric argument to binary operator``
which points in the right direction but isn't optimal from my point of view.

**Comment by jgabry** [comment]
Thanks, I agree with all of that.
>
>

**Comment by jgabry** [comment]
Ok, I changed it so that `y` can be a vector or 1-D array (which is then coerced to a vector). `yrep` still needs to be a matrix. Both `y` and `yrep` are also now checked for being numeric.

**Comment by paul-buerkner** [comment]
Sounds good to me.
